### ISSUE TITLE
Strange apperance in rename modal for transparent mode

### ISSUE THREAD

**Issue by timsofteng** [omerxx/tmux-sessionx#104] opened 2024-05-28 18:29 UTC
When I try to rename session in my terminal with transparent bg I see this 
<img width="1300" alt="image" src="https://github.com/omerxx/tmux-sessionx/assets/51912173/227959f1-b6e4-49fd-a5c3-b2bb0af2e71e">
I guess it looks not very pleasant.
Not a bug however.

I would some borders or so

**Comment by omerxx** [comment] 2024-05-30 09:26
Yep, this is a  challenge with the alternate shell design.
This is a [duplicate of this issue](https://github.com/omerxx/tmux-sessionx/issues/89)
Feel free to reopen if you think otherwise

**Closed by omerxx** 2024-05-30 09:26 UTC
