### ISSUE TITLE
Issue: Unable to Execute the Plugin

### ISSUE THREAD

**Issue by shricodev** [omerxx/tmux-sessionx#45] opened 2024-02-29 15:36 UTC
## Problem

I am not able to run the plugin. This is the config: https://github.com/shricodev/dotfiles/blob/135416e8ab7e6f9b50c7720c27d4ab77a3b3c7e2/tmux/.config/tmux/tmux.conf

I have fairly updated dependencies

![deps_status](https://github.com/omerxx/tmux-sessionx/assets/76906722/dbf23545-cccf-4451-9e48-c0bb1f1422a3)

---

## Already tried

I have installed the plugin, sourced it, and tried changing the default binding, but without any success. :(

**NOTE**: I am using a fish shell `3.7.0`

```bash
.dotfiles on master > fish --version
fish, version 3.7.0
```

**Comment by omerxx** [comment] 2024-03-01 15:09
Hey @shricodev what is the behaviour exactly? A pop up window that instantly disappears? Or nothing at all?
Any chance you try to change the default binding to something else and try again (making sure there's no conflict there).

Also, stating the obvious but just in case - the plugin is installed right? You should be able to see it under your Tmux dir under `plugins`

**Comment by shibisuriya** [comment] 2024-03-01 17:23
One of the things that I have observed is that when you override the default keymaps of sessionx in tmux.conf file, the plugin doesn't go back to its default keymaps even after you remove the settings from tmux.conf and <prefix>I to make tpm reinstall everything...

**Comment by shricodev** [comment] 2024-03-01 17:30
@omerxx Nothing shows up at all. I have made sure that it is installed and even tried changing the bindings to ‘q,’ for example.

![installed_tmux_plugins](https://github.com/omerxx/tmux-sessionx/assets/76906722/40766fd2-b114-43d8-ab93-3ca39ccfc839)
![nvimtree_tmux](https://github.com/omerxx/tmux-sessionx/assets/76906722/9aadd5d2-080b-474f-84ab-185a48fcdd42)

I don't think but maybe the problem is specific to my shell, `fish` 🤷‍♂️. I will try it with `Zsh` and let you know.
If possible, could you try stowing my Neovim dotfile config on your local system and see if it works for you?

**Comment by omerxx** [comment] 2024-03-01 21:00
I'd really love to hear whether ZSH does the trick. Although I did have fish users running the plugin (with other issues such as renaming etc). Please let me know so we can document this and maybe find a solution.

I'll try to reproduce but it'll take a while 🙏🏽

**Comment by shricodev** [comment] 2024-03-02 04:39
@omerxx, I installed and switched my shell to ZSH, but it did not help either. Now I think this issue may be somewhat related to my machine configs since, I don't have conflicting bindings for tmux. Perhaps something isn't right, and I need to figure out where. Yes, please try to reproduce this locally.

Also, for reference, I am using WSL if that matters. Closing the issue for now; feel free to reopen the issue after reproducing or if someone else faces the same issue in the future to discuss it further.

**Comment by ibrittez** [comment] 2024-05-25 21:31
Hi! by any chance you were trying to use it with tmux 3.2?

**Comment by sasank-desaraju** [comment] 2024-06-30 01:09
I am in a similar boat where I am running Zsh on Pop_OS 22.04 with fzf, fzf-tmux, bat, and zoxide at latest versions and the plugin is not working. I tried put in an echo statement at the top of tmux-sessionx/sessionx.tmux and it does not print.

**Comment by ibrittez** [comment] 2024-06-30 02:17
Have you checked your tmux version?? The default apt version on 22.04 its tmux 3.2a, at least for me it doesn't work

**Comment by sasank-desaraju** [comment] 2024-06-30 05:05
I upgraded to next-3.5 before posting and it did not work :/
Here is more info about my versions:
[
![Screenshot from 2024-06-30 01-05-16](https://github.com/omerxx/tmux-sessionx/assets/32106144/dded91fb-5569-4f73-a62b-5ed7cc1f5c7b)
](url)

**Comment by ibrittez** [comment] 2024-07-01 03:56
In my case after updating tmux, everything its working with this versions:

```
~ % tmux -V
tmux 3.4
~ % fzf --version
0.52.1 (6432f00)
~ % fzf-tmux --version
fzf-tmux (with fzf 0.52.1 (6432f00))
 ~ % bat --version 
bat 0.24.0 (fc95468)
~ % zoxide --version
zoxide 0.9.4
```
I don't know what the next-tmux versions are. Did you try "normal" tmux?

**Comment by sasank-desaraju** [comment] 2024-07-29 17:28
I am sorry for my very late response.
I just checked again and the plugin seems to be working!
My package versions seem to be the same as before and I am still running Pop_OS! 22.04.
I do not know what is different about now.
Thank you all for your help!
![Package versions from today](https://github.com/user-attachments/assets/98632be1-9462-412e-9178-3eb14a5a6415)

**Comment by omerxx** [comment] 2024-09-23 18:02
> I am sorry for my very late response. I just checked again and the plugin seems to be working! My package versions seem to be the same as before and I am still running Pop!_OS 22.04. I do not know what is different about now. Thank you all for your help! ![Package versions from today](https://private-user-images.githubusercontent.com/32106144/353171752-98632be1-9462-412e-9178-3eb14a5a6415.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxMTQ4NDQsIm5iZiI6MTcyNzExNDU0NCwicGF0aCI6Ii8zMjEwNjE0NC8zNTMxNzE3NTItOTg2MzJiZTEtOTQ2Mi00MTJlLTkxNzgtM2ViMTRhNWE2NDE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDE4MDIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4NDViNjg5MTk1MWY3MzA4ZmNjZTUzNTVjZTVkMjIzNmQyZTk0NWFmZjVlMWI4OTc1NjdhYTQ3MjgzOGY4MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ymn9wGxJtBkZ7NXSVOd6ZdcZEChD2OzFcug1SRxExKE)

Happy to hear!

I'm closing this issue for now, if anyone stumbles upon this and upgrading tmux isn't doing the trick, please reopne

**Closed by omerxx** 2024-09-23 18:02 UTC
