### ISSUE TITLE
Plugin Issue with tmux 3.2 Resolved in 3.4 ¿Missing prerequisite?

### ISSUE THREAD

**Issue by ibrittez** [omerxx/tmux-sessionx#102] opened 2024-05-25 21:29 UTC
Hi! I just installed the plugin with tmux 3.2 and it didn't work. When I opened it with version 3.2 and pressed prefix-O, no floating window appeared, and tmux froze, forcing me to close it. After updating to 3.4, the plugin works perfectly. Maybe the issue wasn't related to the version, and my previous tmux installation was faulty for some reason.

**Comment by ProgmRuanSilva** [comment] 2024-05-26 00:08
Hey @ibrittez thanks for opening this issue.

Yesterday I went through something similar, but it was the ncurses lib. Don't know if that was the case in your case, or if it was something similar.

**Comment by omerxx** [comment] 2024-05-30 20:32
Hi @ibrittez. Not sure, if you can reproduce this and confirm that 3.2 is infact not supported because of a feature we use then I'll make sure it's pointed out.
That said, 3.2 (and previous versions) already had popups - [release notes here](https://raw.githubusercontent.com/tmux/tmux/3.2/CHANGES) so I don't think this has to do with the version.

With your permission I'll close this, but feel free to reopen if you think this becomes relevant again

**Closed by omerxx** 2024-05-30 20:32 UTC
