### ISSUE TITLE
Hide sessions

### ISSUE THREAD

**Issue by snikoletopoulos** [omerxx/tmux-sessionx#140] opened 2024-09-09 14:02 UTC
It would be useful to be able to hide sessions by name.

This way we could have hidden sessions, for example for floax.

example:
```
set -g @sessionx-hidden-sessions 'scratch,background-session'
```

**Comment by omerxx** [comment] 2024-09-17 11:41
Totally. This is a duplicate of #95 
I'm on it :)

**Closed by omerxx** 2024-09-17 11:41 UTC
